### ISSUE TITLE
使用时没有任何显示

### ISSUE THREAD

**Issue by s-yh-china** [TISUnion/Task#2]
MCDR版本: 0.7.1
服务端版本: paper-163 1.15.2
情况复现:
在游戏内输入!!task help游戏内没有任何显示,而服务器后台提示没有这个指令.
后来使用任何!!task的指令都出现了此问题
通过查看文件发现是正常运行并可以添加,但就是没有显示

**Comment by Fallen-Breath** [comment]
有用MCDR分支吗

**Comment by Fallen-Breath** [comment]
算了原作者咕了我把mcdr合并过去算了

**Comment by dogdie233** [comment]
把stext.py里的"/tellraw"全部替换成"tellraw"即可

**Comment by Ra1ny-Yuki** [comment]
代码早已重构，该issue应被清理
